// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xkcvbtrjgabgfgqzanwx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhrY3ZidHJqZ2FiZ2ZncXphbnd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg2MTEwNjgsImV4cCI6MjA2NDE4NzA2OH0.CxjtzAyCu5TB9uScHv6QGTu3nJEJujEHnzANALir0Tg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);